document: feedback-pipeline-workload
version: 1
data:
  name: qt5 eln-extra packages
  description: QT5 ELN Extras packages
  maintainer: tdawson
  labels:
    - eln-extras
  packages:
    - qt5-doc
    - qt5-qt3d
    - qt5-qtbase
    - qt5-qtcharts
    - qt5-qtconnectivity
    - qt5-qtdatavis3d
    - qt5-qtdeclarative
    - qt5-qtdoc
    - qt5-qtgamepad
    - qt5-qtgraphicaleffects
    - qt5-qtimageformats
    - qt5-qtlocation
    - qt5-qtmultimedia
    - qt5-qtnetworkauth
    - qt5-qtquickcontrols
    - qt5-qtquickcontrols2
    - qt5-qtremoteobjects
    - qt5-qtscript
    - qt5-qtscxml
    - qt5-qtsensors
    - qt5-qtserialbus
    - qt5-qtserialport
    - qt5-qtspeech
    - qt5-qtsvg
    - qt5-qttools
    - qt5-qttranslations
    - qt5-qtvirtualkeyboard
    - qt5-qtwayland
    - qt5-qtwebchannel
    - qt5-qtwebsockets
    - qt5-qtx11extras
    - qt5-qtxmlpatterns
    - qt5-rpm-macros
    - qt5-srpm-macros
